# Generated by Django 6.0.6 on 2026-06-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('phone', 'Phone'), ('charger', 'Charger'), ('cord', 'Cord'), ('others', 'Others')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('avaliable', 'Avaliable'), ('unavaliable', 'Unavaliable')], default='active', max_length=20),
        ),
    ]
